<<<<<<< HEAD
version: "3.8"
services:
  app:
    build: .
    container_name: task-notes-app
    ports:
      - "80:3000"
    volumes:
      - ./public:/app/public
      - ./tasks.db:/app/tasks.db
      - ./taskmaster.db:/app/taskmaster.db
      - .:/app      # Mount entire folder (careful with dev)
    environment:
      - NODE_ENV=production
    restart: always
=======
version: "3.8"

services:
  app:
    build: .
    container_name: task-notes-app
    ports:
      - "80:3000"   # EC2 port 80 maps to container 3000
    volumes:
      - .:/app      # Mount entire folder so SQLite can create files freely
    environment:
      - NODE_ENV=production
    restart: always
>>>>>>> 33de035
